services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - mern-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI
      - JWT_SECRET
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo:latest
    container_name: mongodb-container
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

volumes:
  mongodb-data:

networks:
  mern-network:
    driver: bridge